### ISSUE TITLE
Allow 'getAddresses' to increment from a non-standard path index

### ISSUE THREAD

**Issue by KevinVitale** [GridPlus/gridplus-sdk#174]
The MetaMask fork allows users to specify different derivation path indexes (standard, Ledger Live, Ledger Legacy). As it were, the `getAddresses` call instructs the hardware to increment `n` number of addresses at the last path index for standard derivation only, and any other path index requires a client-specific implementation (see `gridplus/eth-lattice-keyring`) to enumerate `n` calls on `getAddresses`.

As the number of clients integrating with Lattice1 grows, it's worth considering allowing `getAddresses` to increment a non-standard path index, making it easier for feature-parity across clients.

**Comment by alex-miller-0** [comment]
This should already be possible, with two important caveats:

* The `coin_type` must be a known value. Currently only supported coin types are ETH (`60'`), BTC (`0'`), and BTC_TESTNET (`1'`). This restriction ensures firmware can produce addresses of known formatting.
* `skipCache` must be set to `true`. This is because we only cache certain types of addresses in firmware. I'd like to deprecate caching all together, but for now we can just suggest apps use `skipCache=true`.

Here's an example of a nonstandard path being requested: https://github.com/GridPlus/gridplus-sdk/blob/dev/test/testWalletJobs.js#L225
