### ISSUE TITLE
Add latency stress-testing framework

### ISSUE THREAD

**Issue by KevinVitale** [GridPlus/gridplus-sdk#219]

**Comment by alex-miller-0** [comment]
We validated the latency in question was MetaMask-related and couldn't be teased out in the SDK . Here's the latency test suite I wrote, though we may remove the branch at some point since it doesn't really do anything: https://github.com/GridPlus/gridplus-sdk/commit/c45f4b2d3c2b6504e3456228a664621ea64ca9e9
